#!/usr/bin/env python3
"""HD webcam body tracking using OpenCV + MediaPipe.

This script opens a connected webcam, runs full-body pose tracking,
and displays live landmark overlays in a video window.
"""

import argparse
import sys
import time

import cv2
import mediapipe as mp


def list_cameras(max_devices=8):
    cameras = []
        for index in range(max_devices):
                cap = cv2.VideoCapture(index)
                        if not cap.isOpened():
                                    cap.release()
                                                continue
                                                        ret, _ = cap.read()
                                                                if ret:
                                                                            cameras.append(index)
                                                                                    cap.release()
                                                                                        return cameras


                                                                                        def parse_camera_arg(camera_arg):
                                                                                            if camera_arg is None:
                                                                                                    return 0
                                                                                                        if camera_arg.isdigit():
                                                                                                                return int(camera_arg)
                                                                                                                    return camera_arg


                                                                                                                    def open_camera(camera, width=1280, height=720):
                                                                                                                        cap = cv2.VideoCapture(camera)
                                                                                                                            if not cap.isOpened():
                                                                                                                                    raise RuntimeError(f"Could not open camera: {camera}")

                                                                                                                                        cap.set(cv2.CAP_PROP_FRAME_WIDTH, width)
                                                                                                                                            cap.set(cv2.CAP_PROP_FRAME_HEIGHT, height)
                                                                                                                                                return cap


                                                                                                                                                def draw_fps(frame, fps):
                                                                                                                                                    text = f"FPS: {fps:.1f}"
                                                                                                                                                        cv2.putText(frame, text, (16, 32), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0, 255, 0), 2)


                                                                                                                                                        def draw_camera_label(frame, camera):
                                                                                                                                                            label = f"Camera: {camera}"
                                                                                                                                                                cv2.putText(frame, label, (16, 60), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (255, 255, 255), 2)


                                                                                                                                                                def main():
                                                                                                                                                                    parser = argparse.ArgumentParser(description="OpenCV + MediaPipe full-body pose tracking")
                                                                                                                                                                        parser.add_argument("--camera", default=None, help="Camera index or device path (e.g. 0 or /dev/video0)")
                                                                                                                                                                            parser.add_argument("--list-cameras", action="store_true", help="List available camera indices and exit")
                                                                                                                                                                                parser.add_argument("--width", type=int, default=1280, help="Capture width")
                                                                                                                                                                                    parser.add_argument("--height", type=int, default=720, help="Capture height")
                                                                                                                                                                                        parser.add_argument("--min-detection-confidence", type=float, default=0.5, help="Pose detection confidence threshold")
                                                                                                                                                                                            parser.add_argument("--min-tracking-confidence", type=float, default=0.5, help="Pose tracking confidence threshold")
                                                                                                                                                                                                args = parser.parse_args()

                                                                                                                                                                                                    if args.list_cameras:
                                                                                                                                                                                                            cameras = list_cameras(max_devices=10)
                                                                                                                                                                                                                    if not cameras:
                                                                                                                                                                                                                                print("No cameras detected. Connect your HD264 USB webcam and try again.")
                                                                                                                                                                                                                                            sys.exit(1)
                                                                                                                                                                                                                                                    print("Detected camera indices:")
                                                                                                                                                                                                                                                            for index in cameras:
                                                                                                                                                                                                                                                                        print(f"  {index}")
                                                                                                                                                                                                                                                                                print("Run with --camera INDEX to open a specific device.")
                                                                                                                                                                                                                                                                                        sys.exit(0)

                                                                                                                                                                                                                                                                                            camera = parse_camera_arg(args.camera)
                                                                                                                                                                                                                                                                                                print(f"Opening camera: {camera}")

                                                                                                                                                                                                                                                                                                    cap = open_camera(camera, width=args.width, height=args.height)

                                                                                                                                                                                                                                                                                                        mp_drawing = mp.solutions.drawing_utils
                                                                                                                                                                                                                                                                                                            mp_pose = mp.solutions.pose

                                                                                                                                                                                                                                                                                                                with mp_pose.Pose(
                                                                                                                                                                                                                                                                                                                        static_image_mode=False,
                                                                                                                                                                                                                                                                                                                                model_complexity=2,
                                                                                                                                                                                                                                                                                                                                        enable_segmentation=False,
                                                                                                                                                                                                                                                                                                                                                min_detection_confidence=args.min_detection_confidence,
                                                                                                                                                                                                                                                                                                                                                        min_tracking_confidence=args.min_tracking_confidence,
                                                                                                                                                                                                                                                                                                                                                            ) as pose:
                                                                                                                                                                                                                                                                                                                                                                    prev_time = time.time()
                                                                                                                                                                                                                                                                                                                                                                            while cap.isOpened():
                                                                                                                                                                                                                                                                                                                                                                                        success, frame = cap.read()
                                                                                                                                                                                                                                                                                                                                                                                                    if not success:
                                                                                                                                                                                                                                                                                                                                                                                                                    print("Failed to read frame from camera.")
                                                                                                                                                                                                                                                                                                                                                                                                                                    break

                                                                                                                                                                                                                                                                                                                                                                                                                                                image_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                                                                                                                                                                                                                                                                                                                                                                                                                                                            image_rgb.flags.writeable = False
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        results = pose.process(image_rgb)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    image_rgb.flags.writeable = True
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                output_frame = cv2.cvtColor(image_rgb, cv2.COLOR_RGB2BGR)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if results.pose_landmarks:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            mp_drawing.draw_landmarks(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                output_frame,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    results.pose_landmarks,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        mp_pose.POSE_CONNECTIONS,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            landmark_drawing_spec=mp_drawing.DrawingSpec(color=(0, 255, 0), thickness=2, circle_radius=2),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                connection_drawing_spec=mp_drawing.DrawingSpec(color=(0, 128, 255), thickness=2, circle_radius=2),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            current_time = time.time()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fps = 1.0 / (current_time - prev_time) if current_time != prev_time else 0.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    prev_time = current_time

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                draw_fps(output_frame, fps)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            draw_camera_label(output_frame, camera)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cv2.imshow("Body Tracking - Press 'q' to quit", output_frame)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if cv2.waitKey(1) & 0xFF == ord("q"):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    break

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cap.release()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cv2.destroyAllWindows()


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                main()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                